name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:    
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -v
      env:
        GOARCH: "386"
        GOOS: linux
    - uses: actions/upload-artifact@v2
      with:
        name: rsockstun-linux-386
        path: rsockstun
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -v
      env:
        GOARCH: amd64
        GOOS: linux
    - uses: actions/upload-artifact@v2
      with:
        name: rsockstun-linux-amd64
        path: rsockstun
  release-linux-arm:
    name: release linux/arm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -v
      env:
        GOARCH: "arm"
        GOOS: linux
    - uses: actions/upload-artifact@v2
      with:
        name: rsockstun-linux-arm
        path: rsockstun
  release-linux-arm64:
    name: release linux/arm64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -v
      env:
        GOARCH: arm64
        GOOS: linux
    - uses: actions/upload-artifact@v2
      with:
        name: rsockstun-linux-arm64
        path: rsockstun
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -v
      env:
        GOARCH: amd64
        GOOS: darwin
    - uses: actions/upload-artifact@v2
      with:
        name: rsockstun-linux-amd64
        path: rsockstun
  release-windows-386:
    name: release windows/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -v
      env:
        GOARCH: "386"
        GOOS: windows
    - uses: actions/upload-artifact@v2
      with:
        name: rsockstun-windows-386
        path: rsockstun.exe
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -v
      env:
        GOARCH: amd64
        GOOS: windows
    - uses: actions/upload-artifact@v2
      with:
        name: rsockstun-windows-amd64
        path: rsockstun.exe
